################################### Default Configuration ############################
baseurl = "https://hosenpack.netlify.app/"
title = "HosenPack | Pack Easy"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here
